# Generated by Django 5.0.3 on 2024-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'managed': True, 'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'managed': True, 'verbose_name': 'productimage', 'verbose_name_plural': 'productimages'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'managed': True, 'verbose_name': 'size', 'verbose_name_plural': 'sizes'},
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='name',
        ),
        migrations.AddField(
            model_name='productimages',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='number'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='color',
            table='',
        ),
        migrations.AlterModelTable(
            name='productimages',
            table='',
        ),
        migrations.AlterModelTable(
            name='size',
            table='',
        ),
    ]
