# Generated by Django 5.0.3 on 2024-03-09 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 17, 35, 59, 448158, tzinfo=datetime.timezone.utc), verbose_name='create_datetime'),
        ),
    ]
