# Generated by Django 5.0.3 on 2024-03-09 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_create_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'managed': True, 'verbose_name': 'orderitem', 'verbose_name_plural': 'orderitems'},
        ),
        migrations.AlterField(
            model_name='order',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 22, 1, 55, 666948, tzinfo=datetime.timezone.utc), verbose_name='create_datetime'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='',
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table='',
        ),
    ]
